### ISSUE TITLE
안녕하세요.

### ISSUE THREAD

**Issue by dodujy27** [seohayeon/sookmyeong-kakao-i#2]

**Comment by simi0207** [comment]
엥 그런적 없습니다.

- MIT 라이센스 소프트웨어를 취급할 땐 사용한 소프트웨어의 저작권 허가 표시를 모든 복제물이나 중요한 부분에 기재해야한다.
- MIT 라이센스 소프트웨어를 사용해서 발생한 문제는 저작권자가 책임지지 않는다.

Mit 라이선스면 저작자이름 표시해야 하는데 저작권 개념이 없으신건가.....

**Comment by dodujy27** [comment]
![1618030964280.jpg](https://user-images.githubusercontent.com/80041815/114258967-75650200-9a05-11eb-8f72-a1930d9313c4.jpg)

근데 이런 사진 보여주시면서 아직 도와주시고 있다는데 맞나요?
